[2021-01-15 13:48:14,463::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:83@__init__](PID220164:MainProcess): DNS Resolver Nameservers: ['2a01:4f8:0:1::add:9898', '213.133.98.98', '2a01:4f8:0:1::add:9999', '213.133.99.99', '2a01:4f8:0:1::add:1010', '213.133.100.100']
[2021-01-15 13:48:14,464::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:86@__init__](PID220164:MainProcess): DNS Resolver (Nameservers) Port: {}
[2021-01-15 13:48:14,464::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:89@__init__](PID220164:MainProcess): DNS Resolver Port: 53
[2021-01-15 13:48:14,464::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:90@__init__](PID220164:MainProcess): DNS Resolver timeout: 2.0
[2021-01-15 13:48:14,464::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:91@__init__](PID220164:MainProcess): DNS Resolver lifetime: 5.0
[2021-01-15 13:48:14,464::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:92@__init__](PID220164:MainProcess): DNS Resolver over TCP: False
[2021-01-15 14:04:04,189::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:83@__init__](PID338482:MainProcess): DNS Resolver Nameservers: ['2a01:4f8:0:1::add:9898', '213.133.98.98', '2a01:4f8:0:1::add:9999', '213.133.99.99', '2a01:4f8:0:1::add:1010', '213.133.100.100']
[2021-01-15 14:04:04,189::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:86@__init__](PID338482:MainProcess): DNS Resolver (Nameservers) Port: {}
[2021-01-15 14:04:04,190::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:89@__init__](PID338482:MainProcess): DNS Resolver Port: 53
[2021-01-15 14:04:04,190::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:90@__init__](PID338482:MainProcess): DNS Resolver timeout: 2.0
[2021-01-15 14:04:04,190::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:91@__init__](PID338482:MainProcess): DNS Resolver lifetime: 5.0
[2021-01-15 14:04:04,190::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:92@__init__](PID338482:MainProcess): DNS Resolver over TCP: False
[2021-01-16 10:25:21,637::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:83@__init__](PID918448:MainProcess): DNS Resolver Nameservers: ['2a01:4f8:0:1::add:9898', '213.133.98.98', '2a01:4f8:0:1::add:9999', '213.133.99.99', '2a01:4f8:0:1::add:1010', '213.133.100.100']
[2021-01-16 10:25:21,637::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:86@__init__](PID918448:MainProcess): DNS Resolver (Nameservers) Port: {}
[2021-01-16 10:25:21,637::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:89@__init__](PID918448:MainProcess): DNS Resolver Port: 53
[2021-01-16 10:25:21,638::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:90@__init__](PID918448:MainProcess): DNS Resolver timeout: 2.0
[2021-01-16 10:25:21,638::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:91@__init__](PID918448:MainProcess): DNS Resolver lifetime: 5.0
[2021-01-16 10:25:21,638::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:92@__init__](PID918448:MainProcess): DNS Resolver over TCP: False
[2021-03-17 14:47:17,257::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:83@__init__](PID5197:MainProcess): DNS Resolver Nameservers: ['2a01:4f8:0:1::add:9898', '213.133.98.98', '2a01:4f8:0:1::add:9999', '213.133.99.99', '2a01:4f8:0:1::add:1010', '213.133.100.100']
[2021-03-17 14:47:17,257::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:86@__init__](PID5197:MainProcess): DNS Resolver (Nameservers) Port: {}
[2021-03-17 14:47:17,257::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:89@__init__](PID5197:MainProcess): DNS Resolver Port: 53
[2021-03-17 14:47:17,257::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:90@__init__](PID5197:MainProcess): DNS Resolver timeout: 2.0
[2021-03-17 14:47:17,258::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:91@__init__](PID5197:MainProcess): DNS Resolver lifetime: 5.0
[2021-03-17 14:47:17,258::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:92@__init__](PID5197:MainProcess): DNS Resolver over TCP: False
[2021-11-20 07:10:52,699::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:83@__init__](PID1248003:MainProcess): DNS Resolver Nameservers: ['2a01:4f8:0:1::add:9898', '213.133.98.98', '2a01:4f8:0:1::add:9999', '213.133.99.99', '2a01:4f8:0:1::add:1010', '213.133.100.100']
[2021-11-20 07:10:52,699::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:86@__init__](PID1248003:MainProcess): DNS Resolver (Nameservers) Port: {}
[2021-11-20 07:10:52,700::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:89@__init__](PID1248003:MainProcess): DNS Resolver Port: 53
[2021-11-20 07:10:52,700::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:90@__init__](PID1248003:MainProcess): DNS Resolver timeout: 2.0
[2021-11-20 07:10:52,700::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:91@__init__](PID1248003:MainProcess): DNS Resolver lifetime: 5.0
[2021-11-20 07:10:52,700::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:92@__init__](PID1248003:MainProcess): DNS Resolver over TCP: False
[2021-11-20 07:10:53,707::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:83@__init__](PID1248011:MainProcess): DNS Resolver Nameservers: ['2a01:4f8:0:1::add:9898', '213.133.98.98', '2a01:4f8:0:1::add:9999', '213.133.99.99', '2a01:4f8:0:1::add:1010', '213.133.100.100']
[2021-11-20 07:10:53,707::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:86@__init__](PID1248011:MainProcess): DNS Resolver (Nameservers) Port: {}
[2021-11-20 07:10:53,707::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:89@__init__](PID1248011:MainProcess): DNS Resolver Port: 53
[2021-11-20 07:10:53,707::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:90@__init__](PID1248011:MainProcess): DNS Resolver timeout: 2.0
[2021-11-20 07:10:53,707::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:91@__init__](PID1248011:MainProcess): DNS Resolver lifetime: 5.0
[2021-11-20 07:10:53,707::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:92@__init__](PID1248011:MainProcess): DNS Resolver over TCP: False
[2021-11-20 07:17:03,846::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:83@__init__](PID1249319:MainProcess): DNS Resolver Nameservers: ['2a01:4f8:0:1::add:9898', '213.133.98.98', '2a01:4f8:0:1::add:9999', '213.133.99.99', '2a01:4f8:0:1::add:1010', '213.133.100.100']
[2021-11-20 07:17:03,846::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:86@__init__](PID1249319:MainProcess): DNS Resolver (Nameservers) Port: {}
[2021-11-20 07:17:03,846::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:89@__init__](PID1249319:MainProcess): DNS Resolver Port: 53
[2021-11-20 07:17:03,846::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:90@__init__](PID1249319:MainProcess): DNS Resolver timeout: 2.0
[2021-11-20 07:17:03,846::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:91@__init__](PID1249319:MainProcess): DNS Resolver lifetime: 5.0
[2021-11-20 07:17:03,846::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:92@__init__](PID1249319:MainProcess): DNS Resolver over TCP: False
[2021-11-20 07:17:04,875::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:83@__init__](PID1249327:MainProcess): DNS Resolver Nameservers: ['2a01:4f8:0:1::add:9898', '213.133.98.98', '2a01:4f8:0:1::add:9999', '213.133.99.99', '2a01:4f8:0:1::add:1010', '213.133.100.100']
[2021-11-20 07:17:04,876::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:86@__init__](PID1249327:MainProcess): DNS Resolver (Nameservers) Port: {}
[2021-11-20 07:17:04,876::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:89@__init__](PID1249327:MainProcess): DNS Resolver Port: 53
[2021-11-20 07:17:04,876::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:90@__init__](PID1249327:MainProcess): DNS Resolver timeout: 2.0
[2021-11-20 07:17:04,876::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:91@__init__](PID1249327:MainProcess): DNS Resolver lifetime: 5.0
[2021-11-20 07:17:04,876::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:92@__init__](PID1249327:MainProcess): DNS Resolver over TCP: False
[2021-12-01 08:38:22,768::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:83@__init__](PID8311:MainProcess): DNS Resolver Nameservers: ['2a01:4f8:0:1::add:9898', '213.133.98.98', '2a01:4f8:0:1::add:9999', '213.133.99.99', '2a01:4f8:0:1::add:1010', '213.133.100.100']
[2021-12-01 08:38:22,770::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:86@__init__](PID8311:MainProcess): DNS Resolver (Nameservers) Port: {}
[2021-12-01 08:38:22,770::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:89@__init__](PID8311:MainProcess): DNS Resolver Port: 53
[2021-12-01 08:38:22,770::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:90@__init__](PID8311:MainProcess): DNS Resolver timeout: 2.0
[2021-12-01 08:38:22,770::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:91@__init__](PID8311:MainProcess): DNS Resolver lifetime: 5.0
[2021-12-01 08:38:22,770::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:92@__init__](PID8311:MainProcess): DNS Resolver over TCP: False
[2021-12-01 08:38:23,753::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:83@__init__](PID8544:MainProcess): DNS Resolver Nameservers: ['2a01:4f8:0:1::add:9898', '213.133.98.98', '2a01:4f8:0:1::add:9999', '213.133.99.99', '2a01:4f8:0:1::add:1010', '213.133.100.100']
[2021-12-01 08:38:23,753::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:86@__init__](PID8544:MainProcess): DNS Resolver (Nameservers) Port: {}
[2021-12-01 08:38:23,753::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:89@__init__](PID8544:MainProcess): DNS Resolver Port: 53
[2021-12-01 08:38:23,753::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:90@__init__](PID8544:MainProcess): DNS Resolver timeout: 2.0
[2021-12-01 08:38:23,753::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:91@__init__](PID8544:MainProcess): DNS Resolver lifetime: 5.0
[2021-12-01 08:38:23,753::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:92@__init__](PID8544:MainProcess): DNS Resolver over TCP: False
[2021-12-01 08:40:57,825::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.10/site-packages/PyFunceble/lookup/dns.py:83@__init__](PID9962:MainProcess): DNS Resolver Nameservers: ['2a01:4f8:0:1::add:9898', '213.133.98.98', '2a01:4f8:0:1::add:9999', '213.133.99.99', '2a01:4f8:0:1::add:1010', '213.133.100.100']
[2021-12-01 08:40:57,825::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.10/site-packages/PyFunceble/lookup/dns.py:86@__init__](PID9962:MainProcess): DNS Resolver (Nameservers) Port: {}
[2021-12-01 08:40:57,825::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.10/site-packages/PyFunceble/lookup/dns.py:89@__init__](PID9962:MainProcess): DNS Resolver Port: 53
[2021-12-01 08:40:57,825::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.10/site-packages/PyFunceble/lookup/dns.py:90@__init__](PID9962:MainProcess): DNS Resolver timeout: 2.0
[2021-12-01 08:40:57,825::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.10/site-packages/PyFunceble/lookup/dns.py:91@__init__](PID9962:MainProcess): DNS Resolver lifetime: 5.0
[2021-12-01 08:40:57,825::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.10/site-packages/PyFunceble/lookup/dns.py:92@__init__](PID9962:MainProcess): DNS Resolver over TCP: False
[2021-12-01 08:40:58,748::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.10/site-packages/PyFunceble/lookup/dns.py:83@__init__](PID9970:MainProcess): DNS Resolver Nameservers: ['2a01:4f8:0:1::add:9898', '213.133.98.98', '2a01:4f8:0:1::add:9999', '213.133.99.99', '2a01:4f8:0:1::add:1010', '213.133.100.100']
[2021-12-01 08:40:58,748::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.10/site-packages/PyFunceble/lookup/dns.py:86@__init__](PID9970:MainProcess): DNS Resolver (Nameservers) Port: {}
[2021-12-01 08:40:58,748::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.10/site-packages/PyFunceble/lookup/dns.py:89@__init__](PID9970:MainProcess): DNS Resolver Port: 53
[2021-12-01 08:40:58,748::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.10/site-packages/PyFunceble/lookup/dns.py:90@__init__](PID9970:MainProcess): DNS Resolver timeout: 2.0
[2021-12-01 08:40:58,748::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.10/site-packages/PyFunceble/lookup/dns.py:91@__init__](PID9970:MainProcess): DNS Resolver lifetime: 5.0
[2021-12-01 08:40:58,748::DEBUG::/home/mitchellkrog/.conda/envs/phishing-links/lib/python3.10/site-packages/PyFunceble/lookup/dns.py:92@__init__](PID9970:MainProcess): DNS Resolver over TCP: False
